apiVersion: v1
kind: Service
metadata:
  name: pntasg-service
spec:
  selector:
    app: pntasg                
  ports:
  - protocol: TCP
    port: 3000                    
    targetPort: 8080              
  type: LoadBalancer  